version: '3.4'

services:
  typescriptnode:
    image: typescriptnode
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9000:9000
